---
- name: Include remove default MOTD files
  ansible.builtin.include_tasks: remove_default_motd.yml

- name: Deploy custom MOTD script
  ansible.builtin.template:
    src: motd.sh.j2
    dest: /etc/profile.d/motd.sh
    owner: root
    group: root
    mode: '0644'
  