---
- name: Set Zabbix config path on Windows
  set_fact:
    win_zabbix_config_path: 'C:\Program Files\Zabbix Agent\zabbix_agentd.conf'

- name: Read UserParameters template content
  set_fact:
    falcon_userparameters: "{{ lookup('template', 'falcon_userparameters.conf.j2') }}"

- name: Insert Falcon UserParameters block into Zabbix config
  win_blockinfile:
    path: "{{ win_zabbix_config_path }}"
    block: "{{ falcon_userparameters }}"
    marker: "; {mark} FALCON_MONITORING"

- name: Restart Zabbix Agent service
  win_service:
    name: "Zabbix Agent"
    state: restarted
