- name: Set Zabbix config path and Windows temp path
  set_fact:
    win_zabbix_config_path: 'C:\Program Files\Zabbix Agent\zabbix_agentd.conf'
    win_temp_param_file: 'C:\Users\ansibleawx\Downloads\falcon_userparameters.conf'

- name: Render Falcon UserParameters template directly on Windows host
  win_template:
    src: falcon_userparameters.conf.j2
    dest: "{{ win_temp_param_file }}"

- name: Read lines of Falcon UserParameters from rendered file
  win_shell: Get-Content -Path "{{ win_temp_param_file }}"
  register: falcon_userparam_output

- name: Append each UserParameter line to Zabbix config
  ansible.windows.win_lineinfile:
    path: "C:\\Program Files\\Zabbix Agent\\zabbix_agentd.conf"
    line: "{{ item }}"
    state: present
  loop: "{{ lookup('file', 'rendered_userparameters.conf').splitlines() | reject('equalto', '') | list }}"

- name: Restart Zabbix Agent service
  win_service:
    name: "Zabbix Agent"
    state: restarted
