---
openvpn_client:
  dev: tun
  proto: udp
  remote: 192.168.100.34
  port: 1194
  resolv_retry: infinite
  nobind: true
  persist_key: true
  persist_tun: true
  verb: 3
  ca: ca
  client: qa
  ovpn: qa
  cipher: AES-256-CBC
  tls_cipher: "DEFAULT:@SECLEVEL=0"
