---
- name: Download Zabbix repository package for Ubuntu 22.04
  become: true
  ansible.builtin.get_url:
    url: "{{ ubuntu22_repo }}"
    dest: /tmp/zabbix-release_latest_7.4+ubuntu22.04_all.deb
    mode: '0644'

- name: Install Zabbix repository package
  become: true
  ansible.builtin.apt:
    deb: /tmp/zabbix-release_latest_7.4+ubuntu22.04_all.deb
    state: present
  register: zabbix_repo

- name: Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
  when: zabbix_repo is changed

- name: Install Zabbix Agent2 and plugins
  become: true
  ansible.builtin.apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-mongodb
      - zabbix-agent2-plugin-mssql
      - zabbix-agent2-plugin-postgresql
    state: present

# ---------------- Agent Configuration ----------------

- name: Set Zabbix server parameters
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Server='
    line: "Server={{ zabbix_server }}"
  notify: Restart zabbix-agent2

- name: Set active Zabbix server parameters
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^ServerActive='
    line: "ServerActive={{ zabbix_server }}"
  notify: Restart zabbix-agent2

- name: Set agent hostname
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Hostname='
    line: "Hostname={{ inventory_hostname }}"
  notify: Restart zabbix-agent2

- name: Deploy custom userparameter config if defined
  become: true
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "/etc/zabbix/zabbix_agent2.d/{{ item.key }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ zabbix_custom_userparams | dict2items }}"
  when: zabbix_custom_userparams is defined
  notify: Restart zabbix-agent2

- name: Enable and start Zabbix Agent2
  become: true
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: true
    state: started
