---
- name: Download Zabbix repository package for Ubuntu 22.04
  become: true
  ansible.builtin.get_url:
    url: "{{ ubuntu22_repo }}"
    dest: /tmp/zabbix-release_latest_7.4+ubuntu22.04_all.deb
    mode: '0644'

- name: Install Zabbix repository package
  become: true
  ansible.builtin.apt:
    deb: /tmp/zabbix-release_latest_7.4+ubuntu22.04_all.deb
    state: present

# 🔑 Explicitly import the GPG key and repo file because dpkg sometimes skips it
- name: Ensure Zabbix APT repository file is present
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/zabbix.list
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/zabbix-official.gpg] https://repo.zabbix.com/zabbix/7.4/ubuntu jammy main

- name: Import Zabbix GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Zabbix Agent2 and plugins
  become: true
  ansible.builtin.apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-mongodb
      - zabbix-agent2-plugin-mssql
      - zabbix-agent2-plugin-postgresql
    state: present

# ---------------- Agent Configuration ----------------

- name: Set Zabbix server parameters
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Server='
    line: "Server={{ zabbix_server }}"
  notify: Restart zabbix-agent2

- name: Set active Zabbix server parameters
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^ServerActive='
    line: "ServerActive={{ zabbix_server }}"
  notify: Restart zabbix-agent2

- name: Set agent hostname
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Hostname='
    line: "Hostname={{ inventory_hostname }}"
  notify: Restart zabbix-agent2

- name: Deploy custom userparameter config if defined
  become: true
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "/etc/zabbix/zabbix_agent2.d/{{ item.key }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ zabbix_custom_userparams | dict2items }}"
  when: zabbix_custom_userparams is defined
  notify: Restart zabbix-agent2

- name: Enable and start Zabbix Agent2
  become: true
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: true
    state: started
