---
- name: Add Zabbix 7.4 APT repository manually
  become: true
  copy:
    dest: /etc/apt/sources.list.d/zabbix.list
    content: |
      deb "{{ ubuntu22.04 }}" jammy main
      deb-src "{{ ubuntu22.04 }}" jammy main
    owner: root
    group: root
    mode: '0644'

- name: Add Zabbix GPG key
  become: true
  apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Zabbix Agent2
  become: true
  apt:
    name: 
    - zabbix-agent2
    - zabbix-agent2-plugin-mongodb 
    - zabbix-agent2-plugin-mssql 
    - zabbix-agent2-plugin-postgresql
    state: present

- name: Ensure Zabbix Agent2 is running and enabled
  become: true
  systemd:
    name: zabbix-agent2
    enabled: yes
    state: started

# ---------------- Agent Configuration ----------------

- name: Set Zabbix server parameters
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Server='
    line: "Server={{ zabbix_server }}"
  notify: Restart zabbix-agent2

- name: Set active Zabbix server parameters
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^ServerActive='
    line: "ServerActive={{ zabbix_server }}"
  notify: Restart zabbix-agent2

- name: Set agent hostname
  become: true
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Hostname='
    line: "Hostname={{ inventory_hostname }}"
  notify: Restart zabbix-agent2

- name: Deploy custom userparameter config if defined
  become: true
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "/etc/zabbix/zabbix_agent2.d/{{ item.key }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ zabbix_custom_userparams | dict2items }}"
  when: zabbix_custom_userparams is defined
  notify: Restart zabbix-agent2

- name: Enable and start Zabbix Agent2
  become: true
  ansible.builtin.systemd:
    name: zabbix-agent2
    enabled: true
    state: started
