---
- name: Copy Falcon Sensor .deb from local files directory
  copy:
    src: "falcon-sensor_7.25.0-17804_amd64.deb" # This .deb file is applicable for ubuntu versions 16/18/20/22/24
    dest: "/tmp/falcon-sensor_7.25.0-17804_amd64.deb"
    mode: '0644'

- name: Install Falcon Sensor on Debian
  apt:
    deb: /tmp/falcon-sensor_7.25.0-17804_amd64.deb
    state: present

- name: Register Falcon Sensor with CrowdStrike
  command: /opt/CrowdStrike/falconctl -s --cid="{{ CUSTOMER_ID }}" -f

- name: Set CrowdStrike tags
  command: /opt/CrowdStrike/falconctl -s --tags="{{ crowdstrike_tags }}" -f
  when: crowdstrike_tags is defined

- name: Start Falcon Sensor with SysVinit
  ansible.builtin.service:
    name: falcon-sensor
    state: started
    enabled: yes
  when: ansible_service_mgr == "sysvinit"

- name: Start Falcon Sensor with systemd
  ansible.builtin.systemd:
    name: falcon-sensor
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

# To set alias of falconctl add this line in ~/.bashrc 
# alias falconctl='/opt/CrowdStrike/falconctl'