---
- name: Copy Falcon Sensor installer to Windows host
  win_copy:
    src: "FalconSensor_Windows.exe"
    dest: C:\Users\ansibleawx\Downloads\FalconSensor_Windows.exe
    force: yes

- name: Install Falcon Sensor on Windows
  win_command: C:\Users\ansibleawx\Downloads\FalconSensor_Windows.exe /install /quiet /norestart CID=<Paste CID Here> GROUPING_TAGS={{ crowdstrike_tags }} /log=C:\Logs\CrowdStrikeInstall.log

- name: Ensure Falcon Sensor service is running
  win_service:
    name: "CSFalconService"
    start_mode: auto
    state: started
