---
#- name: Include RHEL 7 download and install tasks
#  include_tasks: download_rhel7.yml
#  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

#- name: Include Debian download and install tasks
#  include_tasks: download_debian.yml
#  when: ansible_os_family == "Debian"

- name: Include Windows download and install tasks
  include_tasks: download_windows.yml
  when: ansible_os_family == "Windows"

