- name: Check if zabbix-agent2 is installed
  shell: rpm -q zabbix-agent2
  register: agent2_installed
  changed_when: false
  failed_when: false

- name: Skip upgrade if zabbix-agent2 already installed
  debug:
    msg: "zabbix-agent2 already installed, skipping host"
  when: agent2_installed.rc == 0

- name: Perform Zabbix Agent 2 upgrade if not installed
  block:
    - name: Find which old config exists
      stat:
        path: "{{ item }}"
      loop: "{{ old_conf_paths }}"
      register: old_conf_candidates

    - name: Set old config path fact
      set_fact:
        old_conf_path: "{{ item.stat.path }}"
      loop: "{{ old_conf_candidates.results }}"
      when: item.stat.exists

    - name: Backup old zabbix-agent config
      copy:
        src: "{{ old_conf_path }}"
        dest: "{{ old_conf_path }}.bak"
        remote_src: yes

    - name: Stop and disable old zabbix-agent service
      service:
        name: zabbix-agent
        state: stopped
        enabled: no

    - name: Install Zabbix repo RPM for CentOS 7
      ansible.builtin.command: "rpm -Uvh {{ centos7_repo }}"
      args:
        creates: /etc/yum.repos.d/zabbix.repo

    - name: Install zabbix-agent2 and plugins
      yum:
        name:
          - zabbix-agent2
          - zabbix-agent2-plugin-mongodb
          - zabbix-agent2-plugin-mssql
          - zabbix-agent2-plugin-postgresql
        state: present

    - name: Backup new zabbix-agent2 config
      copy:
        src: /etc/zabbix/zabbix_agent2.conf
        dest: /etc/zabbix/zabbix_agent2.conf.bak
        remote_src: yes

    - name: Copy old config into new agent2 config
      copy:
        src: "{{ old_conf_path }}"
        dest: /etc/zabbix/zabbix_agent2.conf
        remote_src: yes

    - name: Enable and restart zabbix-agent2
      service:
        name: zabbix-agent2
        state: restarted
        enabled: yes

  when: agent2_installed.rc != 0
