---
- name: Join the server to the AD domain with custom FQDN
  command: >
    echo '{{ bind_password }}' | adcli join
    --domain={{ domain_name }}
    --host-fqdn={{ ansible_fqdn }}.{{ domain_name }}
    --domain-ou="OU=Computers,OU={{ ou_in_zurple_corp_ad }},OU=zurple-corp-ad,DC=zurple-corp-ad,DC=zurple,DC=com"
    --login-user={{ admin_user }}
    --stdin-password
    --verbose


# In case if script facing issue while running command realm join then you can manually join by running command on particular server, command is below
# realm join -v --user=admin zurple-corp-ad.zurple.com
# And command to add record in Active Directory Organization Unit is below
# adcli join --domain=zurple-corp-ad.zurple.com --host-fqdn=<your-hostname>.zurple-corp-ad.zurple.com --domain-ou="OU=Computers,OU=Stage02,OU=zurple-corp-ad,DC=zurple-corp-ad,DC=zurple,DC=com" --login-user=admin --verbose
#
# Example of OU zurple-corp-ad.zurple.com/zurple-corp-ad/Stage02/Computers
