---
- name: Joining the server with Active Directory
  become: yes
  become_user: root
  become_method: sudo
  expect:
    command: "realm join -v --user={{ admin_user }} {{ domain_name }}"
    responses:
      "Password for .*:": "{{ bind_password }}"  # If your password contains any symbol which is used by /bin/bash shell as a command or parameter then you need to use this expect module, otherwise you can use below command which is commented
  #command: echo '{{ bind_password }}' | realm join -v --user={{ admin_user }} {{ domain_name }}
  register: join_output
  no_log: True
  ignore_errors: yes

- name: Display success message
  debug:
    msg: "Join successful!"
  when: join_output.rc == 0

- name: Display error message
  debug:
    msg: "Join failed or already joined"
  when: join_output.rc != 0

## If joining failes due to some error then manually join it with below command
## realm join -v --user=admin zurple-corp-ad.zurple.com