---
- name: Including task for Almalinux9/Redhat9
  ansible.builtin.include_tasks: almalinux9_agent2.yml
  when:
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version == "9"

- name: Including task for ubuntu22.04
  ansible.builtin.include_tasks: ubuntu22_agent2.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "22"

- name: Including task for Windows Server
  ansible.builtin.include_tasks: windows_server_agent2.yml
  when:
    - ansible_os_family == 'Windows'

