---
- name: Create temp directory for Zabbix installer
  ansible.builtin.win_file:
    path: C:\Temp
    state: directory

- name: Download Zabbix Agent2 MSI for Windows
  ansible.builtin.win_get_url:
    url: "{{ windows_server_repo }}"
    dest: C:\Temp\zabbix_agent2.msi

- name: Install Zabbix Agent2 using MSI
  ansible.builtin.win_package:
    path: C:\Temp\zabbix_agent2.msi
    state: present
    arguments: >
      SERVER={{ zabbix_server }}
      SERVERACTIVE={{ zabbix_server }}
      HOSTNAME={{ inventory_hostname }}
      /qn
  register: zabbix_install

- name: Ensure Zabbix Agent 2 service is running
  ansible.builtin.win_service:
    name: "Zabbix Agent 2"
    start_mode: auto
    state: started

- name: Set Zabbix Server
  ansible.builtin.win_lineinfile:
    path: 'C:\Program Files\Zabbix Agent 2\zabbix_agent2.conf'
    regexp: '^Server='
    line: "Server={{ zabbix_server }}"
  register: zabbix_server_config

- name: Set ServerActive
  ansible.builtin.win_lineinfile:
    path: 'C:\Program Files\Zabbix Agent 2\zabbix_agent2.conf'
    regexp: '^ServerActive='
    line: "ServerActive={{ zabbix_server }}"
  register: zabbix_serveractive_config

- name: Set Hostname
  ansible.builtin.win_lineinfile:
    path: 'C:\Program Files\Zabbix Agent 2\zabbix_agent2.conf'
    regexp: '^Hostname='
    line: "Hostname={{ inventory_hostname }}"
  register: zabbix_hostname_config
  
- name: Start and enable Zabbix Agent2 service
  ansible.builtin.win_service:
    name: "Zabbix Agent 2"
    start_mode: auto
    state: "{{ 'restarted' if (zabbix_server_config.changed | default(false)) or (zabbix_serveractive_config.changed | default(false)) or (zabbix_hostname_config.changed | default(false)) else 'started' }}"
    