---
- name: Ensure ~/.local/bin exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
    mode: '0755'

- name: Add ~/.local/bin to PATH (for session)
  set_fact:
    path_with_local_bin: "{{ lookup('env', 'HOME') }}/.local/bin:{{ lookup('env', 'PATH') }}"

- name: Install eksctl to ~/.local/bin
  shell: |
    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
    mv /tmp/eksctl {{ lookup('env', 'HOME') }}/.local/bin/
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/eksctl"
  environment:
    PATH: "{{ path_with_local_bin }}"

- name: Install helm to ~/.local/bin
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/helm"
  environment:
    PATH: "{{ path_with_local_bin }}"

- name: Ensure jq is installed
  package:
    name: jq
    state: present

# ... (rest remains unchanged, just replace all `ansible_env.HOME` with `lookup('env', 'HOME')` and `ansible_env.PATH` with `lookup('env', 'PATH')`)
