---
- name: Overwrite /etc/resolv.conf with custom DNS settings
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    force: true