---
- name: Ensure custom DNS entries are at the very top of /etc/resolv.conf
  blockinfile:
    path: /etc/resolv.conf
    create: yes
    insertafter: BOF
    marker: "# {mark} ANSIBLE MANAGED DNS BLOCK"
    block: |
      search {{ domain_name }}
      nameserver {{ DNS1_IP }}
      nameserver {{ DNS2_IP }}
