---
- name: Update /etc/resolv.conf with custom DNS and search domain
  blockinfile:
    path: /etc/resolv.conf
    create: yes
    block: |
      search {{ domain_name }}
      nameserver {{ DNS1_IP }}
      nameserver {{ DNS2_IP }}
    insertafter: BOF
    marker: "# {mark} ANSIBLE MANAGED DNS BLOCK"
