---
- name: Ensure search domain and DNS servers exist in /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: "{{ item }}"
    state: present
    insertafter: BOF
  loop:
    - "search {{ domain_name }}"
    - "nameserver {{ DNS1_IP }}"
    - "nameserver {{ DNS2_IP }}"
