---
- name: Append lines to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      # AD Domains
      {{ DNS1_IP }} {{ dc_fqdn }}.ms.com {{ dc_fqdn }}
      {{ DNS2_IP }} {{ adc_fqdn }}.ms.com {{ adc_fqdn }}