---
- name: Join Ubuntu server with Active Directory
  become: true
  expect:
    command: >
      realm join -v --user={{ admin_user }}@{{ domain_name }}
      --computer-ou="OU=Computers,OU={{ ENV }},DC=ms,DC=com" {{ domain_name }} --verbose
    responses:
      (?i)password.*: "{{ bind_password }}"
  environment:
    KRB5_CONFIG: /etc/krb5.conf
    PATH: /usr/sbin:/usr/bin:/sbin:/bin
  register: join_output
  ignore_errors: true
  no_log: false  # change to true after success

- name: Show realm join output
  debug:
    var: join_output.stdout

- name: Display success message
  debug:
    msg: "Join successful!"
  when: join_output.rc == 0

- name: Display error message
  debug:
    msg: "Join failed or already joined"
  when: join_output.rc != 0
