---
- name: add session in pam to auto create home directory of AD user's
  pamd:
    name: common-session
    type: session
    control: required
    module_path: pam_mkhomedir.so
    arguments: skel=/etc/skel/ umask=0077
    state: present

    
- name: Restart and Enable Necessary Services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop:
    - sssd
    - sshd
    - oddjobd
    - systemd-logind
    
