---
- name: Add Zabbix repository for AlmaLinux 9
  ansible.builtin.yum:
    name: "{{ almalinux9_repo }}"
    state: present
    disable_gpg_check: true

- name: Upgrade all Zabbix components
  ansible.builtin.yum:
    name: 
      - zabbix-server-mysql
      - zabbix-web
      - zabbix-web-mysql
      - zabbix-apache-conf
      - zabbix-agent2
      - zabbix-sql-scripts
    state: latest
    disable_gpg_check: true

- name: Restart Zabbix server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: Restart Zabbix agent
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
    enabled: yes

- name: Restart Apache
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Check Zabbix server version
  ansible.builtin.command: zabbix_server -V
  register: zbx_ver

- name: Print upgraded version
  ansible.builtin.debug:
    msg: "{{ zbx_ver.stdout }}"
