---
monitored_by: 0        # 0 = Zabbix Server, 1 = Zabbix Proxy
zabbix_proxy: false   # Set to true if monitored via Zabbix Proxy
proxy_id: 9

zabbix_url: "https://zabbix.ms.com/zabbix"
zabbix_user: "{{ zabbix_user }}"
zabbix_pass: "{{ zabbix_pass }}"
zabbix_server: '{{ zabbix_ip }}'

proxy_ip: '10.0.0.37'
zabbix_ip: '10.0.0.36'

host_name: "{{ ansible_hostname }}"
visible_name: "{{ ansible_hostname }}"
host_ip: "{{ ansible_host }}"

# zabbix_groups:
#   - "Zabbix servers"

# zabbix_templates:
#   - "Linux by Zabbix agent"

# Proxy details
# proxy_name: "{{ inventory_hostname }}"
# proxy_ip: "{{ ansible_host }}"
# proxy_mode: 1          # 0 = active, 1 = passive
# proxy_port: "10051"
# proxy_group_name: "zabbix-proxies"
# proxy_hosts: []          # optional, list of host IDs to assign

