--- 
### Zabbix UI
zabbix_groups:
  - "szcoders-prod"
  - "Linux servers"
  - "Proxy Servers"

zabbix_templates:
  - "Linux by Zabbix agent"
  - "ICMP Ping"
  - "Kubernetes nodes by HTTP"
  - "Kubernetes Scheduler by HTTP"
  - "Kubernetes Kubelet by HTTP"
  - "Kubernetes Controller manager by HTTP"
  - "Kubernetes API server by HTTP"

### MOTD Message
motd_env: "Production"
motd_purpose: "Kubernetes Master Node "
motd_logs: "/var/log/messages, /var/log/kubelet.log"
motd_docker: "kubectl logs -n <namespace> <pod-name>"
motd_applications: "Ansible Tower"

### MACROS
zabbix_macros:
  '{$KUBE.API.SERVER.URL}': "http://{{ host_ip }}:6443/metrics"
  '{$KUBE.KUBELET.URL}': "http://{{ host_ip }}:10250/metrics"
  '{$ENV}': "{{ motd_env }}"
  '{$PURPOSE}': "{{ motd_purpose }}"

