---
- name: Install required dependencies
  apt:
    name:
      - gnupg
      - software-properties-common
      - wget
    state: present
    update_cache: yes
  become: true

- name: Download HashiCorp GPG key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: '0644'
  become: true

- name: Add HashiCorp APT repository
  copy:
    dest: /etc/apt/sources.list.d/hashicorp.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main
  become: true

- name: Update APT cache
  apt:
    update_cache: yes
  become: true

- name: Install Terraform
  apt:
    name: terraform
    state: present
  become: true
