---
- name: Installing Terraform
  ansible.builtin.shell: |
    sudo yum install -y yum-utils
    sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo -y
    sudo yum -y install terraform
    