---
- name: Download and install the HashiCorp .repo file
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Terraform
  yum:
    name: terraform
    state: present
