---
- name: Install dependencies
  apt:
    name: 
      - gnupg
      - software-properties-common
      - wget
    state: present
    update_cache: yes

- name: Add HashiCorp GPG key
  ansible.builtin.shell: |
    wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp apt repository
  copy:
    dest: /etc/apt/sources.list.d/hashicorp.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Terraform
  apt:
    name: terraform
    state: present
