---
- name: Add HashiCorp YUM repo
  yum_repository:
    name: hashicorp
    description: "HashiCorp Stable - x86_64"
    baseurl: https://rpm.releases.hashicorp.com/RHEL/7/x86_64/stable
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    enabled: yes

- name: Install Terraform
  yum:
    name: terraform
    state: present
