---
- name: Installing Terraform
  ansible.builtin.shell: |
    yum install -y yum-utils
    yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo -y
    yum -y install terraform
    