---
- name: Install required dependencies
  apt:
    name:
      - gpg
      - wget
    state: present
    update_cache: yes
  become: true

- name: Download and dearmor the HashiCorp GPG key
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true

- name: Add HashiCorp APT repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" \
    > /etc/apt/sources.list.d/hashicorp.list
  args:
    creates: /etc/apt/sources.list.d/hashicorp.list
  become: true

- name: Update APT cache
  apt:
    update_cache: yes
  become: true

- name: Install Terraform
  apt:
    name: terraform
    state: present
  become: true
