---
- name: Include OS-specific install task
  include_tasks: install_ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Include CentOS 7-specific install task
  include_tasks: install_centos7.yml
  when: ansible_distribution == "CentOS"

- name: Include Windows-specific install task
  include_tasks: install_windows.yml
  when: ansible_os_family == "Windows"
