---
- name: Ensure /etc/zurple directory exists with setgid
  ansible.builtin.file:
    path: /etc/zurple
    state: directory
    owner: deploy
    group: zurple
    mode: '2750'  # rwxr-s---
  tags: zurple

- name: Set default ACL for group to r-- on /etc/zurple
  ansible.posix.acl:
    path: /etc/zurple
    default: yes
    entity: ''
    etype: group
    permissions: r
    state: present
  tags: zurple

- name: Set default ACL for others to --- on /etc/zurple
  ansible.posix.acl:
    path: /etc/zurple
    default: yes
    entity: ''
    etype: other
    permissions: '0'  # or '---'
    state: present
  tags: zurple

- name: Create placeholder files in /etc/zurple
  ansible.builtin.copy:
    dest: "/etc/zurple/{{ item.name }}"
    content: ""
    owner: deploy
    group: zurple
    mode: '0640'
    force: no
  loop:
    - { name: 'credentials.ini' }
    - { name: 'credentials.key' }
    - { name: 'platform.ini' }
    - { name: 'platform-php.ini' }
  tags: zurple

- name: Ensure /var/www/zurple.com directory exists
  ansible.builtin.file:
    path: /var/www/zurple.com
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'
  tags: zurple

# - name: Ensure /tmp/cache exists and is owned by www-data
#   ansible.builtin.file:
#     path: /tmp/cache
#     state: directory
#     owner: www-data
#     group: www-data
#     mode: '0755'
#     recurse: true
