---
- name: Check if zabbix-agent2 is already installed
  shell: rpm -q zabbix-agent2
  register: agent2_installed
  ignore_errors: true

- name: Skip upgrade if zabbix-agent2 already installed
  debug:
    msg: "zabbix-agent2 already installed, skipping host"
  when: agent2_installed.rc == 0

- name: Find which old config exists
  stat:
    path: "{{ item }}"
  loop: "{{ old_conf_paths }}"
  register: old_conf_candidates
  when: agent2_installed.rc != 0

- name: Set old config path fact
  set_fact:
    old_conf_path: "{{ item.stat.path }}"
  loop: "{{ old_conf_candidates.results }}"
  when: item.stat.exists and agent2_installed.rc != 0

- name: Backup old zabbix-agent config
  copy:
    src: "{{ old_conf_path }}"
    dest: "{{ old_conf_path }}.bak"
    remote_src: yes
  when: agent2_installed.rc != 0

- name: Stop and disable old zabbix-agent service
  service:
    name: zabbix-agent
    state: stopped
    enabled: no
  when: agent2_installed.rc != 0

- name: Import GPG key for Zabbix
  rpm_key:
    state: present
    key: "{{ zabbix_gpg_key }}"
  when: agent2_installed.rc != 0

- name: Add Zabbix 7.0 repository
  yum:
    name: "{{ zabbix_repo_url }}"
    state: present
  when: agent2_installed.rc != 0

- name: Install zabbix-agent2
  yum:
    name: zabbix-agent2
    state: present
  when: agent2_installed.rc != 0

- name: Backup new zabbix-agent2 config
  copy:
    src: /etc/zabbix/zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf.bak
    remote_src: yes
  when: agent2_installed.rc != 0

- name: Copy old config into new agent2 config
  copy:
    src: "{{ old_conf_path }}"
    dest: /etc/zabbix/zabbix_agent2.conf
    remote_src: yes
  when: agent2_installed.rc != 0

- name: Enable and restart zabbix-agent2
  service:
    name: zabbix-agent2
    state: restarted
    enabled: yes
  when: agent2_installed.rc != 0
