---
- name: Check OS and include relevant task file
  include_tasks: centos7.yml
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

- name: Check OS and include relevant task file
  include_tasks: ubuntu22.yml
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_version'] == '22.04'

- name: Skip unsupported OS
  debug:
    msg: "Skipping unsupported OS: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
  when: not (
          (ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7') or
          (ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution_version'] == '22.04')
        )
