---
- name: Backup new zabbix-agent2 config
  copy:
    src: /etc/zabbix/zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf.bak
    remote_src: yes

- name: Copy old config into new agent2 config
  copy:
    src: "{{ old_conf_path }}"
    dest: /etc/zabbix/zabbix_agent2.conf
    remote_src: yes

- name: Enable and restart zabbix-agent2 service
  service:
    name: zabbix-agent2
    state: restarted
    enabled: yes
