---
- name: Fail if unsupported OS version
  fail:
    msg: "Unsupported OS or version"
  when: >
    (ansible_os_family == "RedHat" and ansible_distribution_major_version | int < 6) or
    (ansible_distribution == "Debian" and ansible_distribution_major_version | int < 7) or
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int < 12)

# RHEL Family (CentOS, AlmaLinux, RHEL, Rocky | >=6)
- name: Include RedHat tasks (RHEL >= 6)
  include_tasks: redhat.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version | int >= 6

# Debian (Debian >= 7)
- name: Include Debian tasks (Debian >= 7)
  include_tasks: debian.yml
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version | int >= 7

# Ubuntu (Ubuntu >= 12)
- name: Include Ubuntu tasks (Ubuntu >= 12)
  include_tasks: ubuntu.yml
  when:
    - ansible_os_family == "Debian"
    - "'Ubuntu' in ansible_distribution"
    - ansible_distribution_major_version | int >= 12

# Windows (no version restriction here)
- name: Include Windows tasks
  include_tasks: windows.yml
  when: ansible_os_family == "Windows"