---
- name: Get AWS Account Information
  amazon.aws.aws_caller_info:
    profile: "{{ account.profile }}"
  register: aws_caller_info

- name: Create/Update NetBox Tenant with Account ID
  netbox.netbox.netbox_tenant:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ current_netbox_tenant }}"
      custom_fields:
        tenet_id: "{{ aws_caller_info.account }}"
    state: present
  register: tenant_result
  retries: 5
  delay: 10
  until: tenant_result is succeeded
  