all:
  vars:
    ansible_user: ansibleawx

  children:
    wazuh:
      hosts:
        wazuh-indexer:
          ansible_host: 192.168.100.76
        wazuh-manager:
          ansible_host: 192.168.100.77

    awx:
      hosts:
        ansible-awx:
          ansible_host: 192.168.100.78

