---
  - name: Create sudo block
    set_fact:
      sudoBlock: "{{ sudoList | join('\n') }}"
    when: sudoList is defined and (sudoList | default([])) | length > 0

  - name: Add Apache2 sudo block
    ansible.builtin.blockinfile:
      path: /etc/sudoers
      block: |
        {{sudoBlock}}
      marker: "# {mark} ANSIBLE APACHE SUDO BLOCK" 
    when: sudoList is defined and (sudoList | default([])) | length > 0

  - name: Set Apache2 ACL
    ansible.builtin.shell: "{{ item }}"
    loop: "{{ aclList }}"
 