---
- name: Install ArgoCD on EKS Dev Cluster
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    kubeconfig_decoded_path: /tmp/kubeconfig-dev  # Path to write decoded kubeconfig
    kubeconfig_path: /tmp/kubeconfig-dev          # Used in all k8s module tasks

  roles:
    - argocd-installation
