# ---
# - name: Install ArgoCD on EKS Dev Cluster
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   vars:
#     kubeconfig_decoded_path: /tmp/kubeconfig-dev
#     kubeconfig_path: /tmp/kubeconfig-dev

#   roles:
#     - argocd-installation

---
- name: Setup ALB Controller and Install ArgoCD on EKS Cluster
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    kubeconfig_decoded_path: /tmp/kubeconfig-dev
    kubeconfig_path: /tmp/kubeconfig-dev

  pre_tasks:
    - name: Set up ALB Controller (as root)
      import_role:
        name: alb-controller
      become: true
      become_method: sudo
      become_user: root
      become_flags: "-n"

  roles:
    - argocd-installation
