---
- name: Test Zabbix host module
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ping Zabbix API
      community.zabbix.zabbix_api_info:
        server_url: "http://192.168.12.136/zabbix"
        login_user: "ansible-api"
        login_password: "Ansible@1234"
      register: result

    - debug:
        var: result
