---
- name: Create host item in Zabbix 7.4 using JSON-RPC + Bearer Token
  hosts: zabbix-proxy.ms.com
  gather_facts: false

  vars:
    zabbix_url: "http://192.168.12.136/zabbix"
    zabbix_user: "Admin"
    zabbix_pass: "zabbix"
    hostid: "10084"   # example
    item_name: "Free disk space on /home/joe/"
    item_key: "vfs.fs.size[/home/joe/,free]"
    interfaceid: "1"

  tasks:
    - name: Get API token
      uri:
        url: "{{ zabbix_url }}/api_jsonrpc.php"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            username: "{{ zabbix_user }}"
            password: "{{ zabbix_pass }}"
          id: 1
        headers:
          Content-Type: "application/json-rpc"
        validate_certs: false
      register: login_response

    - name: Extract token
      set_fact:
        zbx_token: "{{ login_response.json.result }}"

    - debug:
        msg: "Token: {{ zbx_token }}"

    - name: Create item using Bearer token
      uri:
        url: "{{ zabbix_url }}/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json-rpc"
          Authorization: "Bearer {{ zbx_token }}"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "item.create"
          params:
            name: "{{ item_name }}"
            key_: "{{ item_key }}"
            hostid: "{{ hostid }}"
            type: 0
            value_type: 3
            interfaceid: "{{ interfaceid }}"
            delay: 30
          id: 3
        validate_certs: false
      register: item_create

    - debug:
        var: item_create.json
