---
- name: Create host in Zabbix
  hosts: localhost
  gather_facts: no
  collections:
    - community.zabbix

  vars:
    zabbix_api_url: "http://192.168.12.136/zabbix/api_jsonrpc.php"
    zabbix_user: "Admin"
    zabbix_password: "zabbix"

  tasks:
    - name: Check Zabbix API version (no auth required)
      community.zabbix.zabbix_api_info:
        http_login_user: "{{ zabbix_user }}"
        http_login_password: "{{ zabbix_password }}"
      register: zbx_info

    - debug:
        msg: "Connected to Zabbix API version {{ zbx_info.version }}"

    - name: Create or update a Zabbix host
      community.zabbix.zabbix_host:
        url: "{{ zabbix_api_url }}"
        login_user: "{{ zabbix_user }}"
        login_password: "{{ zabbix_password }}"
        host_name: "test-host"
        visible_name: "Test Host"
        description: "Host created via AWX playbook using community.zabbix 3.1.0"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "192.168.12.150"
            dns: ""
            port: "10050"
        host_groups:
          - "Linux servers"
        link_templates:
          - "Template OS Linux"
        status: enabled
        state: present
