---
- name: Manage Zabbix 7.4 hosts using REST API
  hosts: "zabbix-proxy.ms.com"
  gather_facts: false
  vars:
    zabbix_url: "http://192.168.12.136"
    zabbix_user: "Admin"
    zabbix_pass: "zabbix"
    host_name: "zabbix-proxy.ms.com"
    host_ip: "10.0.0.37"

  tasks:
    - name: Get API token
      uri:
        url: "{{ zabbix_url }}/api/v1/session"
        method: POST
        body_format: json
        body:
          username: "{{ zabbix_user }}"
          password: "{{ zabbix_pass }}"
        validate_certs: false
      register: login_response

    - name: Show token
      debug:
        var: login_response.json.token

    - name: Get templates
      uri:
        url: "{{ zabbix_url }}/api/v1/template"
        method: GET
        headers:
          Authorization: "Bearer {{ login_response.json.token }}"
        validate_certs: false
      register: templates

    - debug:
        msg: "Available templates: {{ templates.json | map(attribute='host') | list }}"

    - name: Create host
      uri:
        url: "{{ zabbix_url }}/api/v1/host"
        method: POST
        headers:
          Authorization: "Bearer {{ login_response.json.token }}"
        body_format: json
        body:
          host: "{{ host_name }}"
          interfaces:
            - type: 1
              main: 1
              useip: true
              ip: "{{ host_ip }}"
              dns: ""
              port: "10050"
          groups:
            - name: "Linux servers"
          templates:
            - name: "Template OS Linux"
        status_code: [200, 201, 409]
        validate_certs: false
      register: create_host

    - debug:
        var: create_host.json
