---
- name: Create host in Zabbix 7.4 using JSON-RPC + Bearer Token
  hosts: zabbix-proxy.ms.com
  gather_facts: false

  vars:
    zabbix_url: "http://192.168.12.136/zabbix"
    zabbix_user: "Admin"
    zabbix_pass: "zabbix"

    # Host details
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    host_ip: "{{ ansible_host}}"
    group_name: "Linux servers"
    template_name: "Template OS Linux"

  tasks:
    # ---------------------------------------------------------
    - name: Get API token
      uri:
        url: "{{ zabbix_url }}/api_jsonrpc.php"
        method: POST
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            username: "{{ zabbix_user }}"
            password: "{{ zabbix_pass }}"
          id: 1
        headers:
          Content-Type: "application/json-rpc"
        validate_certs: false
      register: login_response

    - set_fact:
        zbx_token: "{{ login_response.json.result }}"

    - debug:
        msg: "Authenticated successfully with token {{ zbx_token }}"

    # ---------------------------------------------------------
    - name: Get host group ID
      uri:
        url: "{{ zabbix_url }}/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json-rpc"
          Authorization: "Bearer {{ zbx_token }}"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "hostgroup.get"
          params:
            filter:
              name: "{{ group_name }}"
            output: ["groupid"]
          id: 2
        validate_certs: false
      register: group_response

    - set_fact:
        group_id: "{{ group_response.json.result[0].groupid }}"

    - debug:
        msg: "Found group ID {{ group_id }} for {{ group_name }}"

    # ---------------------------------------------------------
    - name: Get template ID
      uri:
        url: "{{ zabbix_url }}/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json-rpc"
          Authorization: "Bearer {{ zbx_token }}"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "template.get"
          params:
            filter:
              host: "{{ template_name }}"
            output: ["templateid"]
          id: 3
        validate_certs: false
      register: template_response

    - set_fact:
        template_id: "{{ template_response.json.result[0].templateid }}"

    - debug:
        msg: "Found template ID {{ template_id }} for {{ template_name }}"

    # ---------------------------------------------------------
    - name: Create host using Bearer token
      uri:
        url: "{{ zabbix_url }}/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json-rpc"
          Authorization: "Bearer {{ zbx_token }}"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "host.create"
          params:
            host: "{{ host_name }}"
            name: "{{ visible_name }}"
            interfaces:
              - type: 1          # agent interface
                main: 1
                useip: 1
                ip: "{{ host_ip }}"
                dns: ""
                port: "10050"
            groups:
              - groupid: "{{ group_id }}"
            templates:
              - templateid: "{{ template_id }}"
          id: 4
        validate_certs: false
      register: host_create

    - debug:
        var: host_create.json
