---
- name: Create host in Zabbix
  hosts: localhost
  gather_facts: no
  collections:
    - community.zabbix

  vars:
    zabbix_api_url: "http://192.168.12.136/zabbix/api_jsonrpc.php"
    zabbix_api_token: "224071a8f31e10573a0b622281db35d88e66f6ff5178c826c28df2e982f16337"

  tasks:
    - name: Check Zabbix API version
      community.zabbix.zabbix_api_info:
        url: "{{ zabbix_api_url }}"
        login_token: "{{ zabbix_api_token }}"
      register: zbx_info

    - debug:
        msg: "Connected to Zabbix API version {{ zbx_info.version }}"

    - name: Create or update a Zabbix host
      community.zabbix.zabbix_host:
        url: "{{ zabbix_api_url }}"
        login_token: "{{ zabbix_api_token }}"
        host_name: "test-host"
        visible_name: "Test Host"
        description: "Host created via AWX playbook using community.zabbix 3.1.0"
        interfaces:
          - type: 1          # Agent
            main: 1
            useip: 1
            ip: "192.168.12.150"
            dns: ""
            port: "10050"
        host_groups:
          - "Linux servers"
        link_templates:
          - "Template OS Linux"
        status: enabled
        state: present
