---
- name: Setup ALB Controller and Install ArgoCD on EKS Cluster
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cluster_name: ""
    region: ""
    vpc_id: ""
    aws_account_id: ""
    kubeconfig_decoded_path: /tmp/kubeconfig-dev
    kubeconfig_path: /tmp/kubeconfig-dev
    argocd_namespace: ""

  roles:
    - argocd-installation
    - alb-controller
