---
- name: OpenVPN Installation and Configuration on CentOS 7
  hosts: centos7
  become: true

#  roles:
#    - openvpn

  tasks:
    - name: Create openvpn client keys 
      import_tasks: roles/openvpn/tasks/create_client_key.yml