--- 
- name: Create host
  become: false
  community.zabbix.zabbix_host:
    host_name: "test-host"
    visible_name: "Test Host"
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "10.0.99.99"
        dns: ""
        port: "10050"
    host_groups:
      - name: "Linux servers"
    link_templates:
      - name: "Template OS Linux"
    state: present
    vars:
    ansible_connection: httpapi
    ansible_network_os: community.zabbix.zabbix
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: "zabbix"
    ansible_user: szahid
    ansible_httpapi_pass: "343802S@@di321"

