--- 
- name: Authenticate with Zabbix API
  uri:
    url: "{{ zabbix_url }}/api_jsonrpc.php"
    method: POST
    body_format: json
    return_content: yes
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        user: "{{ zabbix_user }}"
        password: "{{ zabbix_password }}"
      id: 1
    headers:
      Content-Type: "application/json"
  register: login_response

- name: Create host in Zabbix
  uri:
    url: "{{ zabbix_url }}/api_jsonrpc.php"
    method: POST
    body_format: json
    return_content: yes
    body:
      jsonrpc: "2.0"
      method: "host.create"
      params:
        host: "{{ inventory_hostname }}"
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: "{{ ansible_host }}"
            dns: ""
            port: "10050"
        groups:
          - groupid: "{{ zabbix_hostgroup_id }}"
        templates:
          - templateid: "{{ zabbix_template_id }}"
      auth: "{{ login_response.json.result }}"
      id: 2
    headers:
      Content-Type: "application/json"
  when: login_response.json.result is defined