--- 
- name: Set credentials to access Zabbix Server API
  ansible.builtin.set_fact:
    ansible_user: Admin
    ansible_httpapi_pass: zabbix

- name: Add test host to Zabbix
  gather_facts: false
  vars:
    ansible_connection: httpapi
    ansible_network_os: community.zabbix.zabbix
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: "zabbix"  # Change to "zabbixeu" if needed
    # ansible_host: 192.168.12.136            # Zabbix server IP or FQDN
    # ansible_user: Admin
    # ansible_httpapi_pass: zabbix
  become: false
  delegate_to: 192.168.12.136

- name: Create basic test host
  gather_facts: false
  community.zabbix.zabbix_host:
    host_name: "test-host"
    visible_name: "Test Host"
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "10.0.99.99"
        dns: ""
        port: "10050"
    host_groups:
      - name: "szcoders-corp"
    link_templates:
      - name: "Linux by Zabbix agent"
    state: present

