---
# - name: Ensure host exists on Zabbix UI
#   become: false
#   community.zabbix.zabbix_host:
#     server_url: "{{ zabbix_api_url }}"
#     login_user: "{{ zabbix_api_user }}"
#     login_password: "{{ zabbix_api_password }}"
#     host_name: "{{ zabbix_host_name }}"
#     visible_name: "{{ zabbix_host_name }}"
#     groups: "{{ zabbix_host_groups }}"
#     templates: "{{ zabbix_host_templates }}"
#     interfaces: "{{ zabbix_host_interfaces }}"
#     state: present
#   delegate_to: localhost

- name: Ensure host exists on Zabbix UI
  become: false
  delegate_to: localhost
  community.zabbix.zabbix_host:
    connection:
      url: "{{ zabbix_api_url }}"
      username: "{{ zabbix_api_user }}"
      password: "{{ zabbix_api_pass }}"
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    status: enabled
    host_groups:
      - "Linux servers"
    link_templates:
      - "Template OS Linux by Zabbix agent"
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_host }}"
        dns: ""
        port: 10050
