---
- name: Register host in Zabbix via API
  local_action:
    module: community.zabbix.zabbix_host
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    description: "{{ zabbix_host_description }}"
    host_groups: "{{ zabbix_host_groups }}"
    link_templates: "{{ zabbix_link_templates }}"
    status: "{{ zabbix_host_status }}"
    state: present
    inventory_mode: disabled
    interfaces:
      - type: "{{ zabbix_interface_type }}"
        main: 1
        useip: "{{ zabbix_interface_use_ip }}"
        ip: "{{ zabbix_interface_ip | default(ansible_host) }}"
        dns: "{{ inventory_hostname }}"
        port: "{{ zabbix_interface_port }}"
  run_once: false
