---
# - name: Ensure host exists on Zabbix UI
#   become: false
#   community.zabbix.zabbix_host:
#     server_url: "{{ zabbix_api_url }}"
#     login_user: "{{ zabbix_api_user }}"
#     login_password: "{{ zabbix_api_password }}"
#     host_name: "{{ zabbix_host_name }}"
#     visible_name: "{{ zabbix_host_name }}"
#     groups: "{{ zabbix_host_groups }}"
#     templates: "{{ zabbix_host_templates }}"
#     interfaces: "{{ zabbix_host_interfaces }}"
#     state: present
#   delegate_to: localhost

- name: Set API token
  ansible.builtin.set_fact:
    ansible_zabbix_auth_key: db26efd4cab4611c67b8d2b2eec6e4cd9a07078c3b2ec6c95776fc85ec587e45