--- 
- name: Create a new host or rewrite an existing host's info (Zabbix <= 7.0)
# Set task level following variables for Zabbix Server host in task
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_zabbix_url_path: "zabbix"  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu
  become: false
  delegate_to: 192.168.12.136
  community.zabbix.zabbix_host:
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    description: "Zabbix Proxy Server"
    host_groups:
      - Virtual machines
      - szcoders-corp
    link_templates:
      - Linux by Zabbix agent
      - ICMP Ping
    status: enabled
    state: present
    inventory_mode: automatic
    # inventory_zabbix:
    #   tag: "{{ your_tag }}"
    #   alias: "{{ your_alias }}"
    #   notes: "Special Informations: {{ your_informations | default('None') }}"
    #   location: "{{ your_location }}"
    #   site_rack: "{{ your_site_rack }}"
    #   os: "{{ your_os }}"
    #   hardware: "{{ your_hardware }}"
    # ipmi_authtype: 2
    # ipmi_privilege: 4
    # ipmi_username: username
    # ipmi_password: password
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: 10.0.0.37
        dns: ""
        port: "10050"
    monitored_by: server
    macros:
      - macro: "{$EXAMPLEMACRO}"
        value: ExampleMacroValue
      - macro: EXAMPLEMACRO2
        value: ExampleMacroValue2
        description: Example desc that work only with Zabbix 4.4 and higher
    tags:
      - tag: ExampleHostsTag
      - tag: ExampleHostsTag2
        value: ExampleTagValue