---
- name: Convert macro dictionary to list format
  set_fact:
    zabbix_template_macro_list: >-
      {% set macros = [] %}
      {% for key, value in zabbix_template_macros.items() %}
        {% set _ = macros.append({'macro': key, 'value': value}) %}
      {% endfor %}
      {{ macros }}

- name: Update macros in Zabbix template
  community.zabbix.zabbix_template:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_user }}"
    login_password: "{{ zabbix_pass }}"
    template_name: "Kubernetes Kubelet by HTTP"
    macros: "{{ zabbix_template_macro_list }}"
    state: present
  when: zabbix_template_macros is defined