--- 
- name: Get API token
  uri:
    url: "{{ zabbix_url }}/api_jsonrpc.php"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        username: "{{ zabbix_user }}"
        password: "{{ zabbix_pass }}"
      id: 1
    headers:
      Content-Type: "application/json-rpc"
    validate_certs: false
  register: login_response

- set_fact:
    zbx_token: "{{ login_response.json.result }}"

# ---------------------------------------------------------
- name: Loop over templates to update macros
  vars:
    template_item: "{{ item }}"
  loop: "{{ zabbix_template_macros }}"
  loop_control:
    label: "{{ item.template_name }}"
  block:

    # 1️⃣ Get template ID
    - name: Get template ID for {{ template_item.template_name }}
      uri:
        url: "{{ zabbix_url }}/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json-rpc"
          Authorization: "Bearer {{ zbx_token }}"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "template.get"
          params:
            filter:
              host: "{{ template_item.template_name }}"
            output: ["templateid", "name"]
          id: 10
        validate_certs: false
      register: template_response

    - set_fact:
        template_id: "{{ template_response.json.result[0].templateid }}"

    - debug:
        msg: "Resolved template ID for {{ template_item.template_name }} → {{ template_id }}"

    # 2️⃣ Update all macros for this template
    - name: Update macros for {{ template_item.template_name }}
      uri:
        url: "{{ zabbix_url }}/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json-rpc"
          Authorization: "Bearer {{ zbx_token }}"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "template.update"
          params:
            templateid: "{{ template_id }}"
            macros: "{{ template_item.macros }}"
        validate_certs: false
      register: template_macro_update_response

    - debug:
        msg: "Macros updated for {{ template_item.template_name }} → {{ template_macro_update_response }}"
