---
- name: Update Zabbix template macros
  community.zabbix.zabbix_template:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_user }}"
    login_password: "{{ zabbix_password }}"
    template_name: "{{ item.template_name }}"
    macros: "{{ item.macros }}"
    state: present
  loop: "{{ zabbix_template_macros }}"
  loop_control:
    label: "{{ item.template_name }}"
    want_list: true
