--- 
- name: Update Macros in Zabbix UI 
  community.zabbix.zabbix_hostmacro:
    host_name: "{{ inventory_hostname }}"
    macro_name: "{$KUBE.KUBELET.URL}"
    macro_value: "http://{{ host_ip }}:10250/metrics"
    macro_description: ""
    state: present
