--- 
- name: Get API token
  uri:
    url: "{{ zabbix_url }}/api_jsonrpc.php"
    method: POST
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "user.login"
      params:
        username: "{{ zabbix_user }}"
        password: "{{ zabbix_pass }}"
      id: 1
    headers:
      Content-Type: "application/json-rpc"
    validate_certs: false
  register: login_response

- set_fact:
    zbx_token: "{{ login_response.json.result }}"

# ---------------------------------------------------------
# Get template ID
- name: Get template ID
  uri:
    url: "{{ zabbix_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zbx_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "template.get"
      params:
        filter:
          host: "{{ template_name }}"
        output: ["templateid", "name"]
      id: 2
    validate_certs: false
  register: template_response

- set_fact:
    template_id: "{{ template_response.json.result[0].templateid }}"

- debug:
    msg: "Resolved template ID: {{ template_id }}"

# ---------------------------------------------------------
# 3️⃣ Get existing template macros
- name: Get existing macros for template
  uri:
    url: "{{ zabbix_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zbx_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "template.get"
      params:
        templateids: ["{{ template_id }}"]
        selectMacros: ["macro", "value"]
      id: 3
    validate_certs: false
  register: template_macros_response

- set_fact:
    existing_template_macro: >-
      {{ (template_macros_response.json.result[0].macros | selectattr('macro', 'equalto', '{$KUBE.KUBELET.URL}') | list)[0] | default({}) }}

- debug:
    msg: "Existing template macro → {{ existing_template_macro }}"

# ---------------------------------------------------------
# 4️⃣ Update template macro (if exists) or add it
- name: Update or add macro in template
  uri:
    url: "{{ zabbix_url }}/api_jsonrpc.php"
    method: POST
    headers:
      Content-Type: "application/json-rpc"
      Authorization: "Bearer {{ zbx_token }}"
    body_format: json
    body:
      jsonrpc: "2.0"
      method: "template.update"
      params:
        templateid: "{{ template_id }}"
        macros:
          - macro: "{$KUBE.KUBELET.URL}"
            value: "http://{{ host_ip }}:10250/metrics"
    validate_certs: false
  register: template_macro_update_response

- debug:
    msg: "Template macro update result → {{ template_macro_update_response.json }}"
