---
- name: Install EPEL repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present

- name: Install Remi repository
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-9.rpm
    state: present
