---
- name: Ensure EPEL repository is installed
  yum:
    name: epel-release
    state: present
  ignore_errors: true

- name: Ensure Remi repository is installed (via RPM URL if not available)
  block:
    - name: Install Remi repository package
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-9.rpm
        state: present
        disable_gpg_check: true
  rescue:
    - name: Fallback to installing Remi repo via yum if URL fails
      yum:
        name: remi-release
        state: present
  ignore_errors: true
