---
- name: Including sssd role for Almalinux/Redhat
  include_role: 
    name: sssd-redhat
  when:
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version == "9"
    - ansible_distribution_version is version('9.6', '==')

- name: Including sssd role for Ubuntu
  include_role: 
    name: sssd-ubuntu
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "22"
    - ansible_distribution_version is version('22.04', '==')

    