---

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Install iptables-services
  yum:
    name: iptables-services
    state: present

- name: Mask and stop firewalld
  systemd:
    name: firewalld
    enabled: false
    masked: true
    state: stopped
  ignore_errors: true  # Prevent failure if firewalld is already masked or broken

- name: Enable and start iptables
  systemd:
    name: iptables
    enabled: true
    state: started

- name: Flush iptables
  command: iptables -F

- name: Add MASQUERADE rule for VPN traffic
  command: iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
  args:
    warn: false

- name: Save iptables rules
  command: iptables-save
  register: iptables_rules

- name: Persist iptables config
  copy:
    content: "{{ iptables_rules.stdout }}"
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: '0644'

- name: Restart network
  systemd:
    name: network
    state: restarted
