---

- name: Copy OpenVPN server config
  copy:
    src: /usr/share/doc/openvpn-2.4.12/sample/sample-config-files/server.conf
    dest: /etc/openvpn/server.conf
    remote_src: yes

- name: Uncomment and set OpenVPN server config lines
  replace:
    path: /etc/openvpn/server.conf
    regexp: '^;?\s*{{ item.key }}.*'
    replace: '{{ item.line }}'
  loop:
    - { key: 'dh', line: 'dh dh2048.pem' }
    - { key: 'push "redirect-gateway', line: 'push "redirect-gateway def1 bypass-dhcp"' }
    - { key: 'push "dhcp-option DNS 8.8.8.8"', line: 'push "dhcp-option DNS 8.8.8.8"' }
    - { key: 'push "dhcp-option DNS 8.8.4.4"', line: 'push "dhcp-option DNS 8.8.4.4"' }
    - { key: 'user nobody', line: 'user nobody' }
    - { key: 'group nobody', line: 'group nobody' }

- name: Comment out tls-auth line
  replace:
    path: /etc/openvpn/server.conf
    regexp: '^tls-auth ta.key 0'
    replace: '#tls-auth ta.key 0'
