---
- name: Deploy Easy-RSA vars file
  template:
    src: vars.j2
    dest: /etc/openvpn/easy-rsa/vars

- name: Ensure correct permissions and executability for Easy-RSA files
  file:
    path: "{{ item }}"
    mode: '0755'
    owner: root
    group: root
  loop:
    - /etc/openvpn/easy-rsa/vars
    - /etc/openvpn/easy-rsa/clean-all
    - /etc/openvpn/easy-rsa/build-ca
    - /etc/openvpn/easy-rsa/build-key-server
    - /etc/openvpn/easy-rsa/build-key
    - /etc/openvpn/easy-rsa/build-dh
    - /etc/openvpn/easy-rsa/pkitool
    - /etc/openvpn/easy-rsa/whichopensslcnf
  become: true

- name: Copy openssl.cnf
  copy:
    src: /etc/openvpn/easy-rsa/openssl-1.0.0.cnf
    dest: /etc/openvpn/easy-rsa/openssl.cnf
    remote_src: yes

- name: Ensure root owns /etc/openvpn recursively
  file:
    path: /etc/openvpn
    owner: root
    group: root
    recurse: yes
    state: directory
  become: true

- name: Clean all existing keys
  shell: | 
    source ./vars
    ./clean-all --batch

  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Initialize the CA (create ca.crt and ca.key)
  shell: |
    source ./vars
    ./pkitool --initca
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Build server key
  shell: |
    source ./vars
    ./pkitool --batch --server server
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Build client key with debug
  shell: |
    source ./vars && \
    sed -i '/CN={{ openvpn_client.client }}/d' keys/index.txt && \
    ./pkitool --batch {{ openvpn_client.client }}
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true
  register: client_keygen

- debug:
    var: client_keygen.stdout_lines

- name: Generate Diffie-Hellman parameters
  shell: |
    source ./vars
    ./build-dh
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Find all .crt, .key, .ovpn files in /etc/openvpn/
  find:
    paths: /etc/openvpn/
    patterns: "*.crt,*.key,*.ovpn"
    use_regex: false
  register: openvpn_files_to_delete

- name: Remove all matching OpenVPN certs and keys
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ openvpn_files_to_delete.files }}"
  no_log: true

- name: Copy server certs and keys
  copy:
    src: "/etc/openvpn/easy-rsa/keys/{{ item }}"
    dest: "/etc/openvpn/{{ item }}"
    remote_src: yes
  loop:
    - "{{ openvpn_client.ca }}.crt"
    - "{{ openvpn_client.client }}.crt"
    - "{{ openvpn_client.client }}.key"
  become: true


