- name: Ensure all Easy-RSA scripts are executable
  file:
    path: "{{ item }}"
    mode: '0755'
  loop: "{{ lookup('ansible.builtin.fileglob', '/etc/openvpn/easy-rsa/*', wantlist=True) }}"
  when: item is file
  become: true

- name: Set Easy-RSA environment variables
  copy:
    dest: /etc/openvpn/easy-rsa/vars
    content: |
      export EASY_RSA="/etc/openvpn/easy-rsa"
      export OPENSSL="openssl"
      export KEY_CONFIG="$EASY_RSA/openssl.cnf"
      export KEY_DIR="$EASY_RSA/keys"
      export KEY_SIZE=2048
      export KEY_COUNTRY="US"
      export KEY_PROVINCE="CA"
      export KEY_CITY="SanFrancisco"
      export KEY_ORG="Zurple"
      export KEY_EMAIL="saad.zahid@zurple.com"
      export KEY_OU="server"
      export KEY_NAME="EasyRSA"
    mode: '0644'
    owner: root
    group: root

- name: Run Easy-RSA key generation
  shell: |
    bash -c "source ./vars && ./clean-all && ./build-ca --batch && ./build-key-server --batch server && ./build-dh"
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Generate CA cert (initca)
  shell: bash -c "source ./vars && ./pkitool --initca"
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Generate server certificate
  shell: bash -c "source ./vars && ./pkitool --batch --server server"
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Generate client certificate
  shell: bash -c "source ./vars && ./pkitool --batch client"
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Copy generated server keys and certs
  copy:
    src: "/etc/openvpn/easy-rsa/keys/"
    dest: "/etc/openvpn/"
    remote_src: yes
  become: true
