---

- name: Create empty vars file if not present
  copy:
    dest: /etc/openvpn/easy-rsa/vars
    content: ""
    force: no  # Avoid overwriting if file exists
    owner: root
    group: root
    mode: '0644'

- name: Configure vars file for key generation
  blockinfile:
    path: /etc/openvpn/easy-rsa/vars
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      export KEY_COUNTRY="US"
      export KEY_PROVINCE="CA"
      export KEY_CITY="SanFrancisco"
      export KEY_ORG="Zurple"
      export KEY_EMAIL="abdul.quddos@z57.com"
      export KEY_OU="server"
      export KEY_NAME="EasyRSA"

- name: Copy openssl.cnf
  copy:
    src: /etc/openvpn/easy-rsa/openssl-1.0.0.cnf
    dest: /etc/openvpn/easy-rsa/openssl.cnf
    remote_src: yes

- name: Clean all existing keys
  command: ./clean-all
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Build CA certificate
  command: ./build-ca --batch
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Build server key
  shell: source ./vars && ./build-key-server server --batch
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Build client key
  command: ./build-key client --batch
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Generate Diffie-Hellman parameters
  command: ./build-dh
  args:
    chdir: /etc/openvpn/easy-rsa


- name: Copy server certs and keys
  copy:
    remote_src: yes
    src: "/etc/openvpn/easy-rsa/keys/{{ item }}"
    dest: "/etc/openvpn/{{ item }}"
  loop:
    - dh2048.pem
    - ca.crt
    - server.crt
    - server.key
