---

- name: Ensure correct permissions and executability for Easy-RSA files
  file:
    path: "{{ item }}"
    mode: '0755'
    owner: root
    group: root
  loop:
    - /etc/openvpn/easy-rsa/vars
    - /etc/openvpn/easy-rsa/clean-all
    - /etc/openvpn/easy-rsa/build-ca
    - /etc/openvpn/easy-rsa/build-key-server
    - /etc/openvpn/easy-rsa/build-dh
  become: true

- name: Comment out conflicting KEY_* values
  lineinfile:
    path: /etc/openvpn/easy-rsa/vars
    regexp: '^export {{ item }}='
    line: '# export {{ item }}=<commented>'
    backrefs: no
    state: present
  loop:
    - KEY_COUNTRY
    - KEY_PROVINCE
    - KEY_CITY
    - KEY_ORG
    - KEY_EMAIL
    - KEY_OU
    - KEY_NAME
    - KEY_CN
    - PKCS11_MODULE_PATH
    - PKCS11_PIN

- name: Insert custom OpenVPN key parameters
  blockinfile:
    path: /etc/openvpn/easy-rsa/vars
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      export KEY_COUNTRY="US"
      export KEY_PROVINCE="CA"
      export KEY_CITY="SanFrancisco"
      export KEY_ORG="Zurple"
      export KEY_EMAIL="saad.zahid@zurple.com"
      export KEY_OU="server"
      export KEY_NAME="EasyRSA"

- name: Copy openssl.cnf
  copy:
    src: /etc/openvpn/easy-rsa/openssl-1.0.0.cnf
    dest: /etc/openvpn/easy-rsa/openssl.cnf
    remote_src: yes

- name: Ensure root owns /etc/openvpn recursively
  file:
    path: /etc/openvpn
    owner: root
    group: root
    recurse: yes
    state: directory
  become: true

- name: Clean all existing keys
  shell: | 
    source /etc/openvpn/easy-rsa/vars
    /etc/openvpn/easy-rsa/clean-all --batch
    /etc/openvpn/easy-rsa/build-ca --batch
    /etc/openvpn/easy-rsa/build-key-server server --batch
    /etc/openvpn/easy-rsa/build-dh --batch
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Initialize the CA (create ca.crt and ca.key)
  shell: |
    source ./vars
    ./pkitool --initca
  args:
    chdir: /etc/openvpn/easy-rsa


- name: Build server key
  shell: |
    source ./vars
    ./pkitool --batch --server server
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Build client key
  command: ./pkitool --batch client
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true

- name: Generate Diffie-Hellman parameters
  command: ./build-dh
  args:
    chdir: /etc/openvpn/easy-rsa
  become: true


- name: Copy server certs and keys
  copy:
    remote_src: yes
    src: "/etc/openvpn/easy-rsa/keys/"
    dest: "/etc/openvpn/"