---

- name: Install OpenVPN and easy-rsa
  yum:
    name:
      - openvpn
      - wget
    state: present

- name: Download Easy-RSA 2.3.3
  get_url:
    url: https://github.com/OpenVPN/easy-rsa-old/archive/2.3.3.tar.gz
    dest: /tmp/easyrsa-2.3.3.tar.gz

- name: Create easy-rsa directory
  file:
    path: /etc/openvpn/easy-rsa/keys
    state: directory
    mode: 0755
    recurse: yes

- name: Copy easy-rsa scripts
  copy:
    src: /usr/share/easy-rsa/3.0/
    dest: /etc/openvpn/easy-rsa/
    remote_src: yes
